In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace =True)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [5]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [6]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

numpy to tensors

In [8]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [14]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels
    
    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [15]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [16]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

define model

In [9]:
import torch.nn as nn

class MySingleNN(nn.Module):
    def __init__(self, features):
        super().__init__()
        self.linear = nn.Linear(features, 1)
        self.sigmoid = nn.Sigmoid() 
    
    def forward(self, features):
        linear_out = self.linear(features)
        out = self.sigmoid(linear_out)
        return out

define parameters

In [10]:
learning_rate = 0.1
epochs = 25

training pipeline

In [17]:
import torch.optim as optim

# create model
model = MySingleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loss function
loss_function = nn.BCELoss()

In [27]:
# define loop
for epoch in range(epochs):
        for batch_features, batch_labels in train_loader:
        #1. forward pass
            y_predict = model(batch_features)

        #2. loss calculate
            loss = loss_function(y_predict, batch_labels.view(-1,1))

        #clear gradients
            optimizer.zero_grad()
    
        #3. backward pass, calculate derivatives
            loss.backward()
        
        #4. param update
            optimizer.step()
            print(f"Epoch: {epoch}, and the loss with it: {loss}")

Epoch: 0, and the loss with it: 0.06672768294811249
Epoch: 0, and the loss with it: 0.015202955342829227
Epoch: 0, and the loss with it: 0.20177215337753296
Epoch: 0, and the loss with it: 0.02904520370066166
Epoch: 0, and the loss with it: 0.032273486256599426
Epoch: 0, and the loss with it: 0.03050195425748825
Epoch: 0, and the loss with it: 0.09246300160884857
Epoch: 0, and the loss with it: 0.045366864651441574
Epoch: 0, and the loss with it: 0.10571122914552689
Epoch: 0, and the loss with it: 0.015209725126624107
Epoch: 0, and the loss with it: 0.03968985751271248
Epoch: 0, and the loss with it: 0.01786429062485695
Epoch: 0, and the loss with it: 0.013519306667149067
Epoch: 0, and the loss with it: 0.03410504385828972
Epoch: 0, and the loss with it: 0.0035755776334553957
Epoch: 1, and the loss with it: 0.0052512530237436295
Epoch: 1, and the loss with it: 0.011943749152123928
Epoch: 1, and the loss with it: 0.05751584842801094
Epoch: 1, and the loss with it: 0.10555454343557358
Epoch: 1, and the loss with it: 0.058925215154886246
Epoch: 1, and the loss with it: 0.0396031029522419
Epoch: 1, and the loss with it: 0.007341050077229738
Epoch: 1, and the loss with it: 0.02815544232726097
Epoch: 1, and the loss with it: 0.068341925740242
Epoch: 1, and the loss with it: 0.030769508332014084
Epoch: 1, and the loss with it: 0.02771989442408085
Epoch: 1, and the loss with it: 0.029858771711587906
Epoch: 1, and the loss with it: 0.18619978427886963
Epoch: 1, and the loss with it: 0.08071340620517731
Epoch: 1, and the loss with it: 0.006277681794017553
Epoch: 2, and the loss with it: 0.03398967534303665
Epoch: 2, and the loss with it: 0.03148103877902031
Epoch: 2, and the loss with it: 0.13124865293502808
Epoch: 2, and the loss with it: 0.008020519278943539
Epoch: 2, and the loss with it: 0.20345115661621094
Epoch: 2, and the loss with it: 0.030089866369962692
Epoch: 2, and the loss with it: 0.00890406034886837
Epoch: 2, and the loss with it: 0.020264752209186554
Epoch: 2, and the loss with it: 0.04223139211535454
Epoch: 2, and the loss with it: 0.03118840791285038
Epoch: 2, and the loss with it: 0.027043117210268974
Epoch: 2, and the loss with it: 0.01477142982184887
Epoch: 2, and the loss with it: 0.13288411498069763
Epoch: 2, and the loss with it: 0.014286688528954983
Epoch: 2, and the loss with it: 0.03746458515524864
Epoch: 3, and the loss with it: 0.024206673726439476
Epoch: 3, and the loss with it: 0.023734988644719124
Epoch: 3, and the loss with it: 0.009425169788300991
Epoch: 3, and the loss with it: 0.020099757239222527
Epoch: 3, and the loss with it: 0.027961261570453644
Epoch: 3, and the loss with it: 0.13835099339485168
Epoch: 3, and the loss with it: 0.03672594577074051
Epoch: 3, and the loss with it: 0.023578176274895668
Epoch: 3, and the loss with it: 0.0478505939245224
Epoch: 3, and the loss with it: 0.012091835960745811
Epoch: 3, and the loss with it: 0.2267802208662033
Epoch: 3, and the loss with it: 0.022867219522595406
Epoch: 3, and the loss with it: 0.09493182599544525
Epoch: 3, and the loss with it: 0.01725107431411743
Epoch: 3, and the loss with it: 0.05517372488975525
Epoch: 4, and the loss with it: 0.07724148035049438
Epoch: 4, and the loss with it: 0.00665033096447587
Epoch: 4, and the loss with it: 0.03342147171497345
Epoch: 4, and the loss with it: 0.0496111661195755
Epoch: 4, and the loss with it: 0.01613856852054596
Epoch: 4, and the loss with it: 0.009951095096766949
Epoch: 4, and the loss with it: 0.05311686545610428
Epoch: 4, and the loss with it: 0.004720013588666916
Epoch: 4, and the loss with it: 0.02463419921696186
Epoch: 4, and the loss with it: 0.02518358640372753
Epoch: 4, and the loss with it: 0.09785060584545135
Epoch: 4, and the loss with it: 0.09393851459026337
Epoch: 4, and the loss with it: 0.01355532743036747
Epoch: 4, and the loss with it: 0.2305562049150467
Epoch: 4, and the loss with it: 0.0013697462854906917
Epoch: 5, and the loss with it: 0.025169048458337784
Epoch: 5, and the loss with it: 0.07790544629096985
Epoch: 5, and the loss with it: 0.09275499731302261
Epoch: 5, and the loss with it: 0.2125083953142166
Epoch: 5, and the loss with it: 0.021357711404561996
Epoch: 5, and the loss with it: 0.018248990178108215
Epoch: 5, and the loss with it: 0.014119544997811317
Epoch: 5, and the loss with it: 0.047566670924425125
Epoch: 5, and the loss with it: 0.09638430178165436
Epoch: 5, and the loss with it: 0.038876745849847794
Epoch: 5, and the loss with it: 0.01348787173628807
Epoch: 5, and the loss with it: 0.0329715758562088
Epoch: 5, and the loss with it: 0.04053308442234993
Epoch: 5, and the loss with it: 0.004312740173190832
Epoch: 5, and the loss with it: 0.0025230234023183584
Epoch: 6, and the loss with it: 0.10451409965753555
Epoch: 6, and the loss with it: 0.03528333455324173
Epoch: 6, and the loss with it: 0.05252566561102867
Epoch: 6, and the loss with it: 0.02009647525846958
Epoch: 6, and the loss with it: 0.009087832644581795
Epoch: 6, and the loss with it: 0.013654389418661594
Epoch: 6, and the loss with it: 0.010809607803821564
Epoch: 6, and the loss with it: 0.2734575569629669
Epoch: 6, and the loss with it: 0.01916476897895336
Epoch: 6, and the loss with it: 0.06827723979949951
Epoch: 6, and the loss with it: 0.0158833060413599
Epoch: 6, and the loss with it: 0.015244031324982643
Epoch: 6, and the loss with it: 0.055425263941287994
Epoch: 6, and the loss with it: 0.02751374989748001
Epoch: 6, and the loss with it: 0.07010014355182648
Epoch: 7, and the loss with it: 0.030639154836535454
Epoch: 7, and the loss with it: 0.015405777841806412
Epoch: 7, and the loss with it: 0.026495788246393204
Epoch: 7, and the loss with it: 0.050551638007164
Epoch: 7, and the loss with it: 0.1117384135723114
Epoch: 7, and the loss with it: 0.04377833753824234
Epoch: 7, and the loss with it: 0.03851784020662308
Epoch: 7, and the loss with it: 0.035686857998371124
Epoch: 7, and the loss with it: 0.050410497933626175
Epoch: 7, and the loss with it: 0.195347860455513
Epoch: 7, and the loss with it: 0.07399167865514755
Epoch: 7, and the loss with it: 0.026806995272636414
Epoch: 7, and the loss with it: 0.016707802191376686
Epoch: 7, and the loss with it: 0.01994120329618454
Epoch: 7, and the loss with it: 0.000308574439259246
Epoch: 8, and the loss with it: 0.0849618911743164
Epoch: 8, and the loss with it: 0.005954324267804623
Epoch: 8, and the loss with it: 0.10550621896982193
Epoch: 8, and the loss with it: 0.05419961363077164
Epoch: 8, and the loss with it: 0.03534087538719177
Epoch: 8, and the loss with it: 0.050184160470962524
Epoch: 8, and the loss with it: 0.044411882758140564
Epoch: 8, and the loss with it: 0.030987145379185677
Epoch: 8, and the loss with it: 0.016234666109085083
Epoch: 8, and the loss with it: 0.014780318364501
Epoch: 8, and the loss with it: 0.1979368031024933
Epoch: 8, and the loss with it: 0.027820969000458717
Epoch: 8, and the loss with it: 0.008578893728554249
Epoch: 8, and the loss with it: 0.057840608060359955
Epoch: 8, and the loss with it: 0.0033006228040903807
Epoch: 9, and the loss with it: 0.027046993374824524
Epoch: 9, and the loss with it: 0.007914074696600437
Epoch: 9, and the loss with it: 0.04146520048379898
Epoch: 9, and the loss with it: 0.014284022152423859
Epoch: 9, and the loss with it: 0.030099213123321533
Epoch: 9, and the loss with it: 0.04657108709216118
Epoch: 9, and the loss with it: 0.038945287466049194
Epoch: 9, and the loss with it: 0.011768657714128494
Epoch: 9, and the loss with it: 0.016901066526770592
Epoch: 9, and the loss with it: 0.036366239190101624
Epoch: 9, and the loss with it: 0.007768813520669937
Epoch: 9, and the loss with it: 0.12353743612766266
Epoch: 9, and the loss with it: 0.2697068154811859
Epoch: 9, and the loss with it: 0.06083056330680847
Epoch: 9, and the loss with it: 0.002796925837174058
Epoch: 10, and the loss with it: 0.05354531109333038
Epoch: 10, and the loss with it: 0.059614576399326324
Epoch: 10, and the loss with it: 0.025158191099762917
Epoch: 10, and the loss with it: 0.011067044921219349
Epoch: 10, and the loss with it: 0.09344711154699326
Epoch: 10, and the loss with it: 0.01052149198949337
Epoch: 10, and the loss with it: 0.12617526948451996
Epoch: 10, and the loss with it: 0.04757995530962944
Epoch: 10, and the loss with it: 0.028866467997431755
Epoch: 10, and the loss with it: 0.03331310302019119
Epoch: 10, and the loss with it: 0.001978629734367132
Epoch: 10, and the loss with it: 0.19419679045677185
Epoch: 10, and the loss with it: 0.024883782491087914
Epoch: 10, and the loss with it: 0.024053756147623062
Epoch: 10, and the loss with it: 0.0006522207404486835
Epoch: 11, and the loss with it: 0.022348269820213318
Epoch: 11, and the loss with it: 0.1715269684791565
Epoch: 11, and the loss with it: 0.02150564268231392
Epoch: 11, and the loss with it: 0.0170693751424551
Epoch: 11, and the loss with it: 0.00919297058135271
Epoch: 11, and the loss with it: 0.19875724613666534
Epoch: 11, and the loss with it: 0.021518591791391373
Epoch: 11, and the loss with it: 0.02716119959950447
Epoch: 11, and the loss with it: 0.015065730549395084
Epoch: 11, and the loss with it: 0.02749195322394371
Epoch: 11, and the loss with it: 0.04758941009640694
Epoch: 11, and the loss with it: 0.02094712294638157
Epoch: 11, and the loss with it: 0.0955100879073143
Epoch: 11, and the loss with it: 0.026021897792816162
Epoch: 11, and the loss with it: 0.05321239307522774
Epoch: 12, and the loss with it: 0.03003428317606449
Epoch: 12, and the loss with it: 0.021699192002415657
Epoch: 12, and the loss with it: 0.11126061528921127
Epoch: 12, and the loss with it: 0.011068166233599186
Epoch: 12, and the loss with it: 0.040686607360839844
Epoch: 12, and the loss with it: 0.04055854678153992
Epoch: 12, and the loss with it: 0.019799107685685158
Epoch: 12, and the loss with it: 0.008993810974061489
Epoch: 12, and the loss with it: 0.01722687855362892
Epoch: 12, and the loss with it: 0.05730275809764862
Epoch: 12, and the loss with it: 0.22709684073925018
Epoch: 12, and the loss with it: 0.011938915587961674
Epoch: 12, and the loss with it: 0.09452784061431885
Epoch: 12, and the loss with it: 0.014997401274740696
Epoch: 12, and the loss with it: 0.11545380204916
Epoch: 13, and the loss with it: 0.0521685965359211
Epoch: 13, and the loss with it: 0.011227725073695183
Epoch: 13, and the loss with it: 0.027185892686247826
Epoch: 13, and the loss with it: 0.22822080552577972
Epoch: 13, and the loss with it: 0.008845659904181957
Epoch: 13, and the loss with it: 0.044709790498018265
Epoch: 13, and the loss with it: 0.12916068732738495
Epoch: 13, and the loss with it: 0.02673817239701748
Epoch: 13, and the loss with it: 0.03282615914940834
Epoch: 13, and the loss with it: 0.004210697021335363
Epoch: 13, and the loss with it: 0.035375237464904785
Epoch: 13, and the loss with it: 0.009461485780775547
Epoch: 13, and the loss with it: 0.028079843148589134
Epoch: 13, and the loss with it: 0.02030114270746708
Epoch: 13, and the loss with it: 0.33907338976860046
Epoch: 14, and the loss with it: 0.018730808049440384
Epoch: 14, and the loss with it: 0.002248496748507023
Epoch: 14, and the loss with it: 0.022233029827475548
Epoch: 14, and the loss with it: 0.13728424906730652
Epoch: 14, and the loss with it: 0.031619004905223846
Epoch: 14, and the loss with it: 0.04755617678165436
Epoch: 14, and the loss with it: 0.023955661803483963
Epoch: 14, and the loss with it: 0.03638021647930145
Epoch: 14, and the loss with it: 0.04132840782403946
Epoch: 14, and the loss with it: 0.07303903996944427
Epoch: 14, and the loss with it: 0.06351147592067719
Epoch: 14, and the loss with it: 0.19365979731082916
Epoch: 14, and the loss with it: 0.02569608762860298
Epoch: 14, and the loss with it: 0.015135076828300953
Epoch: 14, and the loss with it: 0.001860027201473713
Epoch: 15, and the loss with it: 0.02842981368303299
Epoch: 15, and the loss with it: 0.01474372111260891
Epoch: 15, and the loss with it: 0.0638544037938118
Epoch: 15, and the loss with it: 0.04777006804943085
Epoch: 15, and the loss with it: 0.09420575201511383
Epoch: 15, and the loss with it: 0.02248820848762989
Epoch: 15, and the loss with it: 0.18997813761234283
Epoch: 15, and the loss with it: 0.053518809378147125
Epoch: 15, and the loss with it: 0.034951843321323395
Epoch: 15, and the loss with it: 0.03655369579792023
Epoch: 15, and the loss with it: 0.08772222697734833
Epoch: 15, and the loss with it: 0.02715097740292549
Epoch: 15, and the loss with it: 0.014533578418195248
Epoch: 15, and the loss with it: 0.016222547739744186
Epoch: 15, and the loss with it: 0.00018251003348268569
Epoch: 16, and the loss with it: 0.021485544741153717
Epoch: 16, and the loss with it: 0.011021289974451065
Epoch: 16, and the loss with it: 0.02134760469198227
Epoch: 16, and the loss with it: 0.018425162881612778
Epoch: 16, and the loss with it: 0.21034596860408783
Epoch: 16, and the loss with it: 0.054109808057546616
Epoch: 16, and the loss with it: 0.038420166820287704
Epoch: 16, and the loss with it: 0.1487511843442917
Epoch: 16, and the loss with it: 0.010789182037115097
Epoch: 16, and the loss with it: 0.015187682583928108
Epoch: 16, and the loss with it: 0.09989382326602936
Epoch: 16, and the loss with it: 0.016766566783189774
Epoch: 16, and the loss with it: 0.0375639908015728
Epoch: 16, and the loss with it: 0.026553599163889885
Epoch: 16, and the loss with it: 6.946182111278176e-05
Epoch: 17, and the loss with it: 0.01868888922035694
Epoch: 17, and the loss with it: 0.04681370407342911
Epoch: 17, and the loss with it: 0.039504922926425934
Epoch: 17, and the loss with it: 0.018474681302905083
Epoch: 17, and the loss with it: 0.027582164853811264
Epoch: 17, and the loss with it: 0.0737316831946373
Epoch: 17, and the loss with it: 0.011939702555537224
Epoch: 17, and the loss with it: 0.030597331002354622
Epoch: 17, and the loss with it: 0.039650000631809235
Epoch: 17, and the loss with it: 0.028703026473522186
Epoch: 17, and the loss with it: 0.07778605073690414
Epoch: 17, and the loss with it: 0.01592184603214264
Epoch: 17, and the loss with it: 0.007899196818470955
Epoch: 17, and the loss with it: 0.1098901554942131
Epoch: 17, and the loss with it: 0.8402594923973083
Epoch: 18, and the loss with it: 0.0219106525182724
Epoch: 18, and the loss with it: 0.01437466125935316
Epoch: 18, and the loss with it: 0.03825492784380913
Epoch: 18, and the loss with it: 0.0372488871216774
Epoch: 18, and the loss with it: 0.05645902827382088
Epoch: 18, and the loss with it: 0.023781778290867805
Epoch: 18, and the loss with it: 0.033362820744514465
Epoch: 18, and the loss with it: 0.1957838237285614
Epoch: 18, and the loss with it: 0.08390634506940842
Epoch: 18, and the loss with it: 0.021171171218156815
Epoch: 18, and the loss with it: 0.03502510488033295
Epoch: 18, and the loss with it: 0.025448624044656754
Epoch: 18, and the loss with it: 0.01694234274327755
Epoch: 18, and the loss with it: 0.12587858736515045
Epoch: 18, and the loss with it: 0.0036045259330421686
Epoch: 19, and the loss with it: 0.0379641018807888
Epoch: 19, and the loss with it: 0.047133512794971466
Epoch: 19, and the loss with it: 0.023195182904601097
Epoch: 19, and the loss with it: 0.11187296360731125
Epoch: 19, and the loss with it: 0.044054895639419556
Epoch: 19, and the loss with it: 0.0357913114130497
Epoch: 19, and the loss with it: 0.03703749552369118
Epoch: 19, and the loss with it: 0.02663070522248745
Epoch: 19, and the loss with it: 0.019194694235920906
Epoch: 19, and the loss with it: 0.023395800963044167
Epoch: 19, and the loss with it: 0.0312117338180542
Epoch: 19, and the loss with it: 0.011051762849092484
Epoch: 19, and the loss with it: 0.2456032633781433
Epoch: 19, and the loss with it: 0.028427258133888245
Epoch: 19, and the loss with it: 0.03839954361319542
Epoch: 20, and the loss with it: 0.026849528774619102
Epoch: 20, and the loss with it: 0.04630807414650917
Epoch: 20, and the loss with it: 0.02989938296377659
Epoch: 20, and the loss with it: 0.050504498183727264
Epoch: 20, and the loss with it: 0.020157672464847565
Epoch: 20, and the loss with it: 0.10667403042316437
Epoch: 20, and the loss with it: 0.041654471307992935
Epoch: 20, and the loss with it: 0.04616333916783333
Epoch: 20, and the loss with it: 0.027623679488897324
Epoch: 20, and the loss with it: 0.17831942439079285
Epoch: 20, and the loss with it: 0.026434948667883873
Epoch: 20, and the loss with it: 0.01925453543663025
Epoch: 20, and the loss with it: 0.03950841352343559
Epoch: 20, and the loss with it: 0.005729150027036667
Epoch: 20, and the loss with it: 0.2955569624900818
Epoch: 21, and the loss with it: 0.20059049129486084
Epoch: 21, and the loss with it: 0.008943967521190643
Epoch: 21, and the loss with it: 0.06970986723899841
Epoch: 21, and the loss with it: 0.03351061791181564
Epoch: 21, and the loss with it: 0.020912937819957733
Epoch: 21, and the loss with it: 0.06656427681446075
Epoch: 21, and the loss with it: 0.01956692710518837
Epoch: 21, and the loss with it: 0.003556156065315008
Epoch: 21, and the loss with it: 0.01611311174929142
Epoch: 21, and the loss with it: 0.018111595883965492
Epoch: 21, and the loss with it: 0.08783852308988571
Epoch: 21, and the loss with it: 0.05935287103056908
Epoch: 21, and the loss with it: 0.015469135716557503
Epoch: 21, and the loss with it: 0.09955640137195587
Epoch: 21, and the loss with it: 0.045711416751146317
Epoch: 22, and the loss with it: 0.047099217772483826
Epoch: 22, and the loss with it: 0.023091832175850868
Epoch: 22, and the loss with it: 0.09865143895149231
Epoch: 22, and the loss with it: 0.08927455544471741
Epoch: 22, and the loss with it: 0.018391529098153114
Epoch: 22, and the loss with it: 0.19529451429843903
Epoch: 22, and the loss with it: 0.025571968406438828
Epoch: 22, and the loss with it: 0.039304595440626144
Epoch: 22, and the loss with it: 0.025564629584550858
Epoch: 22, and the loss with it: 0.04580789431929588
Epoch: 22, and the loss with it: 0.017029300332069397
Epoch: 22, and the loss with it: 0.016407819464802742
Epoch: 22, and the loss with it: 0.03783092647790909
Epoch: 22, and the loss with it: 0.04214124009013176
Epoch: 22, and the loss with it: 0.03249860927462578
Epoch: 23, and the loss with it: 0.02721191756427288
Epoch: 23, and the loss with it: 0.06564320623874664
Epoch: 23, and the loss with it: 0.1706765592098236
Epoch: 23, and the loss with it: 0.03172812610864639
Epoch: 23, and the loss with it: 0.010018548928201199
Epoch: 23, and the loss with it: 0.042100634425878525
Epoch: 23, and the loss with it: 0.036848247051239014
Epoch: 23, and the loss with it: 0.0055971574038267136
Epoch: 23, and the loss with it: 0.030606083571910858
Epoch: 23, and the loss with it: 0.03263675048947334
Epoch: 23, and the loss with it: 0.028269225731492043
Epoch: 23, and the loss with it: 0.011633515357971191
Epoch: 23, and the loss with it: 0.22055795788764954
Epoch: 23, and the loss with it: 0.010451624169945717
Epoch: 23, and the loss with it: 0.01830754056572914
Epoch: 24, and the loss with it: 0.03645451366901398
Epoch: 24, and the loss with it: 0.027394557371735573
Epoch: 24, and the loss with it: 0.025922205299139023
Epoch: 24, and the loss with it: 0.04513013735413551
Epoch: 24, and the loss with it: 0.22752420604228973
Epoch: 24, and the loss with it: 0.01297636330127716
Epoch: 24, and the loss with it: 0.02713937684893608
Epoch: 24, and the loss with it: 0.01718464493751526
Epoch: 24, and the loss with it: 0.01880032941699028
Epoch: 24, and the loss with it: 0.041857000440359116
Epoch: 24, and the loss with it: 0.02751513570547104
Epoch: 24, and the loss with it: 0.18225571513175964
Epoch: 24, and the loss with it: 0.0253555029630661
Epoch: 24, and the loss with it: 0.0068886615335941315
Epoch: 24, and the loss with it: 0.025214403867721558

evaluation

In [30]:
model.eval() #Set model to evaluation mode, not training anymore
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        y_predict = model(batch_features)
        y_predict = (y_predict > 0.8).float()

        batch_accuracy = (y_predict.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

overall_accuracy =  sum(accuracy_list)/len(accuracy_list)
print(f'Accuracy: {overall_accuracy}')

Accuracy: 0.9704861044883728